CREATE SEQUENCE SEQ_FUNCIONARIO;
CREATE SEQUENCE SEQ_RELOGIO_PONTO;

CREATE TABLE FUNCIONARIO(
  ID_FUNCIONARIO INTEGER NOT NULL,
  NOME VARCHAR2(50),
  COD_BARRAS NUMERIC(14),
  CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO)
);

CREATE TABLE REGISTRO_PONTO(
  ID_REGISTRO_PONTO INTEGER NOT NULL,
  COD_FUNCIONARIO INTEGER NOT NULL,
  DATA_HORA TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_REGISTRO_PONTO PRIMARY KEY(ID_REGISTRO_PONTO),
  CONSTRAINT FK_REGISTRO_PONTO_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

CREATE OR REPLACE TRIGGER TRG_FUNCIONARIO_PK
  BEFORE INSERT ON FUNCIONARIO
  FOR EACH ROW
DECLARE
  xCOD INTEGER;
BEGIN
  IF INSERTING THEN
    SELECT SEQ_FUNCIONARIO.NEXTVAL INTO xCOD FROM DUAL;
    :NEW.ID_FUNCIONARIO := xCOD;
  END IF;
END;

CREATE OR REPLACE TRIGGER TRG_REGISTRO_PONTO_PK
  BEFORE INSERT ON REGISTRO_PONTO
  FOR EACH ROW
DECLARE
  xCOD INTEGER;
BEGIN
  IF INSERTING THEN
    SELECT SEQ_REGISTRO_PONTO.NEXTVAL INTO xCOD FROM DUAL;
    :NEW.ID_REGISTRO_PONTO := xCOD;
  END IF;
END;
